# Generated by Django 6.0.5 on 2026-05-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
