[project]
name = "django-food-order-widget"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.14",
]

# line-length is set to 88 to be compatible with black and ruff
[tool.ruff]
line-length = 88
target-version = "py313"

# Linting rules (E = pycodestyle errors, F = pyflakes, I = isort, B = flake8-bugbear)
# see https://beta.ruff.rs/docs/rules/
[tool.ruff.lint]
select = ["E", "F", "I", "B"]

# Test configuration for pytest
[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]

# Configuration for djlint (Django template linter)
[tool.djlint]
profile = "django"
indent = 2
